### ISSUE TITLE
could not find clog

### ISSUE THREAD

**Issue by tkkcc** [pykeio/ort#288] opened 2024-09-25 15:49 UTC
Hi, i am trying to use ort on android arm64

i build onnxruntime v1.19.2 with following command
```sh
./build.sh --android --android_sdk_path ~/Android/Sdk --android_ndk_path ~/Android/Sdk/ndk/27.0.11718014 --android_abi arm64-v8a --android_api 24 --config Release --parallel --use_nnapi --use_xnnpack --build_java
```
then i set ORT_LIB_LOCATION env before cargo ndk build. ort-sys fail on `println!("cargo:rustc-link-lib=static=clog");`

i searched but can't find clog artifacts
```txt
~/b/onnxruntime fd clog -uuuu                                                                                                                        
build/Android/Release/_deps/pytorch_cpuinfo-src/deps/clog/
build/Android/Release/_deps/pytorch_cpuinfo-src/deps/clog/include/clog.h
build/Android/Release/_deps/pytorch_cpuinfo-src/deps/clog/src/clog.c
build/Android/Release/_deps/pytorch_cpuinfo-src/deps/clog/test/clog.cc
onnxruntime/core/common/logging/sinks/clog_sink.h
```

after commenting out this link, it compiles.

but at runtime, i got this error on load
```txt
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt6__ndk119__shared_weak_countD2Ev"
```
the ort code is only
```rust
    use ort::{GraphOptimizationLevel, Session};
    let model = Session::builder();
```

is my bulid command wrong (°ー°〃), thanks

**Comment by decahedron1** [comment] 2024-09-25 16:02
`clog` issue fixed in https://github.com/pykeio/ort/commit/250222443bfb3417091220e04b8d757d3041c4dd.

I am not familiar with Android, but from similar issues I've found online, it seems the dlopen error is caused by a mismatched API version, and may be resolved by packaging `libc++_shared.so` with the APK, and explicitly loading that library before loading your Rust library.

**Closed by decahedron1** 2024-09-25 16:02 UTC
